### PR TITLE
Disable cut for live videos

### LINKED ISSUE #801: [Crash] App crash on cut button click
### ⠀

- [x] Tried latest version

### ⠀

- [x] This issue is not duplicated with any other open or closed issues

### Describe the bug

When I am click on 'cut' button while configure download setting of a live YouTube video,

App was crash with below logs.

valueFrom(0.0) must be smaller than valueTo(0.0)
com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(SourceFile:525)
com.google.android.material.slider.BaseSlider.onDraw(SourceFile:5)

### Expected behavior

_No response_

### Steps to reproduce

1. Share a link of live YouTube video 
2. Than chose Ytdlins App
3. Than click on 'Cut' Button at the bottom side

### Device information

Device: Vivo T4x 5G
System: Android 15

### Screenshots / Recordings

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by madmini**
Fixes #801. Greys out the cut button if the duration is `0:00` and on tap shows snackbar "Cutting live videos is not supported".

Another possible approach could be to try to parse the duration as timestamp, and if it does not parse or is 0, disable cutting.

Note that I am not familiar with other reasons for invalid durations such as `-1`.

### CODE REVIEW

**Comment by madmini** [comment]
hmm [job failed, seems there is no signing config](https://github.com/deniscerri/ytdlnis/actions/runs/15050264556/job/42303091562#step:11:25), which makes sense for a PR run. But the failed CI did initially scare me 😅

Maybe consider disabling the job entirely for PRs

**Comment by deniscerri** [comment]
@madmini just because a result has 0 duration doesnt mean its live stream. It could also be a broken extractor. I think it would be better if you wrote it in the likes of
Cutting is not available for this item

**Comment by deniscerri** [comment]
Also since you added the timestamp check in uiutil you dont have to do it in audio and video fragment
just throw the snack in uiutil and be done with it

**Comment by madmini** [comment]
okay, but what about the `else if(!nonSpecific)`, which shows a snack with "You need to update the item data in order to be able to use cut feature" and an update button. and during testing this was always the case (and obviously, updating did not change the duration) so i built in the additional check. I had assumed that if there was another error, the duration would be empty or `-1`.

Is there a proper way to differentiate between an invalid duration and incomplete data?

**Comment by deniscerri** [comment]
ah yeah, i forgot about items with no current data. Alright then lets keep it as it is, its looks good. Just change the snack text. Thanks buddy

**Comment by madmini** [comment]
I'd also change the name of the "You need to update the item data in order to be able to use cut feature" from `cut_unavailable` to `cut_unavailable_please_update` or similar, if thats okay. Seems easy to confuse with `cut_unsupported` otherwise.

**Comment by madmini** [comment]
feel free to squash ^^

File: app/src/main/java/com/deniscerri/ytdl/util/UiUtil.kt [hunk 1]
```diff
@@ -1560,10 +1560,8 @@ object UiUtil {
                 }
             }else{
                 cut.alpha = 0.3f
-                if (!invalidDuration) {
-                    cut.setOnClickListener {
-                        cutDisabledClicked()
-                    }
+                cut.setOnClickListener {
```
Comment (deniscerri) [inline app/src/main/java/com/deniscerri/ytdl/util/UiUtil.kt:1563]: One thing here. If duration is invalid like -1, then cut should never be allowed to be clicked, as u can see in previous code. Can you code this in aswell pls? Thnx

Comment (madmini) [reply app/src/main/java/com/deniscerri/ytdl/util/UiUtil.kt:1563]: but if its invalid why not just show the same "cut is not available for this item" snack instead?

Comment (deniscerri) [reply app/src/main/java/com/deniscerri/ytdl/util/UiUtil.kt]: Well you coded it to only trigger that for 0:00, so it will just tell the user to update data which would do nothing it would still bring -1

Comment (madmini) [reply app/src/main/java/com/deniscerri/ytdl/util/UiUtil.kt]: True. What I meant is, why not include `-1` in the if else there (and show "... not available"), instead of blocking it here (like it is now). I am fine with either option, however.

Comment (deniscerri) [reply app/src/main/java/com/deniscerri/ytdl/util/UiUtil.kt]: Ah, if that is the case, then sure go ahead

Comment (madmini) [reply app/src/main/java/com/deniscerri/ytdl/util/UiUtil.kt:1563]: done
